# Ansible Playbook for Subutai Hypothesis Blueprint
--- 

- hosts: rabbitmq
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade packages
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: 
          - dirmngr
          - apt-transport-https
          - ca-certificates
          - sudo
          - locales
          - curl

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Install all that's needed after adding official rabbitmq repos
    # -------------------------------------------------------------------------

    - name: Install rabbitmq repository key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present

    - name: Add binary repository for rabbitmq repo
      apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq-erlang/debian stretch main
        update_cache: true
        state: present
    
    - name: Install rabbitmq-server
      apt:
        name:
          - rabbitmq-server

    - name: Install rabbitmq_management plugin
      rabbitmq_plugin: 
        names: rabbitmq_management
        state: enabled

    - name: Add rabbitmq user
      rabbitmq_user:
        user: "{{ subutai.user_variables.email }}"
        password: "{{ subutai.user_variables.password }}"
        tags: management, administrator
    
    - name: Restart rabbitmq node to have changes take effect
      systemd: 
        name: rabbitmq-server
        state: restarted
        enabled: yes
      
